/*
 * This file was auto-generated by the Axis C++ Web Service Generator (WSDL2Ws)
 * This file contains Client Stub implementation for remote web service.
 */

#include "Mailex.hpp"

#include <axis/AxisWrapperAPI.hpp>
#include <string.h>

using namespace std;

 Mailex::Mailex(const char* pchEndpointUri, AXIS_PROTOCOL_TYPE eProtocol)
:Stub(pchEndpointUri, eProtocol)
{
}

Mailex::Mailex()
:Stub(" ", APTHTTP1_1)
{
	m_pCall->setEndpointURI("http://localhost:8080/mailex/services/Mailex");
	
}

Mailex::~Mailex()
{
}


/*Methods corresponding to the web service methods*/

/*
 * This method wrap the service method getServerVersion
 */
xsd__string Mailex::getServerVersion()
{
	xsd__string Ret;
	memset(&Ret,0,sizeof(xsd__string));
	const char* pcCmplxFaultName;
	try
	{
		if (AXIS_SUCCESS != m_pCall->initialize(CPP_RPC_PROVIDER)) 
			return Ret;
	if (NULL==m_pCall->getTransportProperty("SOAPAction",false))
	{
		m_pCall->setTransportProperty(SOAPACTION_HEADER , "");
	}
		m_pCall->setSOAPVersion(SOAP_VER_1_1);
		m_pCall->setOperation("getServerVersion", "urn:Mailex");
		applyUserPreferences();
		if (AXIS_SUCCESS == m_pCall->invoke())
		{
			if(AXIS_SUCCESS == m_pCall->checkMessage("getServerVersionResponse", "urn:Mailex"))
			{
				Ret = m_pCall->getElementAsString("getServerVersionReturn", 0);
			}
		}
	m_pCall->unInitialize();
		return Ret;
	}
	catch(AxisException& e)
	{
		int iExceptionCode = e.getExceptionCode();
		if(AXISC_NODE_VALUE_MISMATCH_EXCEPTION != iExceptionCode)
		{
			throw SoapFaultException(e);
		}
		ISoapFault* pSoapFault = (ISoapFault*)
			m_pCall->checkFault("Fault","http://localhost:8080/mailex/services/Mailex" );
		if(pSoapFault)
		{
			m_pCall->unInitialize();
			throw SoapFaultException(e);
		}
		else throw;
	}
}


/*
 * This method wrap the service method storeMessage
 */
xsd__boolean Mailex::storeMessage(xsd__base64Binary Value0)
{
	xsd__boolean* Ret = NULL;
	const char* pcCmplxFaultName;
	try
	{
		if (AXIS_SUCCESS != m_pCall->initialize(CPP_RPC_PROVIDER)) 
			return *Ret;
	if (NULL==m_pCall->getTransportProperty("SOAPAction",false))
	{
		m_pCall->setTransportProperty(SOAPACTION_HEADER , "");
	}
		m_pCall->setSOAPVersion(SOAP_VER_1_1);
		m_pCall->setOperation("storeMessage", "urn:Mailex");
		applyUserPreferences();
		m_pCall->addParameter((void*)&Value0, "in0", XSD_BASE64BINARY);
		if (AXIS_SUCCESS == m_pCall->invoke())
		{
			if(AXIS_SUCCESS == m_pCall->checkMessage("storeMessageResponse", "urn:Mailex"))
			{
				Ret = m_pCall->getElementAsBoolean("storeMessageReturn", 0);
			}
		}
	m_pCall->unInitialize();
		//xsd__boolean r = *Ret;
		xsd__boolean r = (xsd__boolean) 1;
		//delete Ret;
		return r;
	}
	catch(AxisException& e)
	{
		int iExceptionCode = e.getExceptionCode();
		if(AXISC_NODE_VALUE_MISMATCH_EXCEPTION != iExceptionCode)
		{
			throw SoapFaultException(e);
		}
		ISoapFault* pSoapFault = (ISoapFault*)
			m_pCall->checkFault("Fault","http://localhost:8080/mailex/services/Mailex" );
		if(pSoapFault)
		{
			m_pCall->unInitialize();
			throw SoapFaultException(e);
		}
		else throw;
	}
}

